import type { NpcPersona } from '@/types';

export const NPC_PERSONAS: Record<string, NpcPersona> = {
  sarah: {
    id: 'sarah',
    name: 'Sarah',
    role: 'Product Manager',
    avatar: '👩‍💼',
    patience: 0.7,
    techSavvy: 0.5,
    politeness: 0.9,
    color: '#00b4d8',
    description: 'Friendly product manager who always has "just one more thing" to add to the sprint.',
    quirk: 'Adds scope to every request mid-conversation',
    preferredApp: 'whatsclaw',
  },
  devdan: {
    id: 'devdan',
    name: 'Dev Dan',
    role: 'Developer',
    avatar: '👨‍💻',
    patience: 0.5,
    techSavvy: 0.95,
    politeness: 0.6,
    color: '#00ff9f',
    description: 'Speaks in code and git commands. Thinks meetings are a bug in the system.',
    quirk: 'Uses tech jargon for everything, even emotions',
    preferredApp: 'teleclaw',
  },
  karen: {
    id: 'karen',
    name: 'Karen',
    role: 'Executive',
    avatar: '👩‍💼',
    patience: 0.3,
    techSavvy: 0.2,
    politeness: 0.4,
    color: '#ff4444',
    description: 'Demands everything NOW. Cc\'s the CEO on every email thread.',
    quirk: 'Threatens to escalate constantly',
    preferredApp: 'whatsclaw',
  },
  timmy: {
    id: 'timmy',
    name: 'Timmy',
    role: 'Intern',
    avatar: '🧑‍🎓',
    patience: 0.9,
    techSavvy: 0.3,
    politeness: 0.8,
    color: '#ffd60a',
    description: 'Eager intern who asks adorable questions. Just happy to be here.',
    quirk: 'Apologizes for asking questions, then asks more',
    preferredApp: 'teleclaw',
  },
  raj: {
    id: 'raj',
    name: 'Raj',
    role: 'DevOps Engineer',
    avatar: '👨‍🔧',
    patience: 0.6,
    techSavvy: 0.9,
    politeness: 0.7,
    color: '#b388ff',
    description: 'Lives in the terminal. Gets paged at 3 AM so often he sleeps in the server room.',
    quirk: 'Checks monitoring dashboards mid-conversation',
    preferredApp: 'teleclaw',
  },
  luna: {
    id: 'luna',
    name: 'Luna',
    role: 'Designer',
    avatar: '👩‍🎨',
    patience: 0.8,
    techSavvy: 0.6,
    politeness: 0.85,
    color: '#ff9f1c',
    description: 'Everything must be pixel-perfect. Notices if something is off by 1px.',
    quirk: 'Adds sparkle emojis to everything',
    preferredApp: 'whatsclaw',
  },
  ghost: {
    id: 'ghost',
    name: 'Ghost',
    role: 'Anonymous',
    avatar: '👻',
    patience: 0.4,
    techSavvy: 0.8,
    politeness: 0.3,
    color: '#6b7280',
    description: 'Nobody knows who this is or how they got access. Probably fine.',
    quirk: 'Speaks in cryptic half-sentences',
    preferredApp: 'teleclaw',
  },
  drchen: {
    id: 'drchen',
    name: 'Dr. Chen',
    role: 'Data Scientist',
    avatar: '👨‍🔬',
    patience: 0.6,
    techSavvy: 0.85,
    politeness: 0.75,
    color: '#00b4d8',
    description: 'Will turn any conversation into a statistics lesson. P-value or it didn\'t happen.',
    quirk: 'Cites statistical significance for mundane decisions',
    preferredApp: 'whatsclaw',
  },
};
